name: Landcover model deployment Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and push the Docker Image to the GitHub Container Registry
      run: 
        docker build ./deployment/ --tag ghcr.io/khaosresearch/deploy-landcover:$(date +%s)
        docker push ghcr.io/khaosresearch/deploy-landcover:$(date +%s)
